//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationOfBusRoute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulationOfBusRoute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bus_editor_button {
            get {
                object obj = ResourceManager.GetObject("bus_editor_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bus_editor_button_active {
            get {
                object obj = ResourceManager.GetObject("bus_editor_button_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_pics {
            get {
                object obj = ResourceManager.GetObject("button_pics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddRouteNodeButton {
            get {
                object obj = ResourceManager.GetObject("mAddRouteNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddRouteNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mAddRouteNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addRouteNodeButton.
        /// </summary>
        internal static string mAddRouteNodeButtonName {
            get {
                return ResourceManager.GetString("mAddRouteNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mRemoveRouteNodeButton {
            get {
                object obj = ResourceManager.GetObject("mRemoveRouteNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mRemoveRouteNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mRemoveRouteNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeRouteNodeButton.
        /// </summary>
        internal static string mRemoveRouteNodeButtonName {
            get {
                return ResourceManager.GetString("mRemoveRouteNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buses.
        /// </summary>
        internal static string mSQLBusesTableName {
            get {
                return ResourceManager.GetString("mSQLBusesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to busStationNodes.
        /// </summary>
        internal static string mSQLBusStationNodesTableName {
            get {
                return ResourceManager.GetString("mSQLBusStationNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crossroadNodes.
        /// </summary>
        internal static string mSQLCrossroadNodesTableName {
            get {
                return ResourceManager.GetString("mSQLCrossroadNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS buses (id INTEGER PRIMARY KEY, name TEXT, position TEXT, velocity REAL, currNumOfPassengers INTEGER, numOfIncomingPassengers INTEGER, numOfExcurrentPassengers INTEGER,  maxNumOfPassengers INTEGER,  currRouteNodeIndex INTEGER, FOREIGN KEY (currRouteNodeIndex) REFERENCES routeNodes(id) ON DELETE CASCADE ON UPDATE CASCADE);.
        /// </summary>
        internal static string mSQLQueryCreateBusesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateBusesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS busStationNodes (id INTEGER, currNumOfPassengers INTEGER, intensity INTEGER, FOREIGN KEY(id) REFERENCES routeNodes(id) ON DELETE CASCADE ON UPDATE CASCADE);.
        /// </summary>
        internal static string mSQLQueryCreateBusStationNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateBusStationNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS crossroadNodes (id INTEGER, loadCoefficient REAL, FOREIGN KEY(id) REFERENCES routeNodes(id) ON DELETE CASCADE ON UPDATE CASCADE);.
        /// </summary>
        internal static string mSQLQueryCreateCrossroadNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateCrossroadNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS routeNodes (id INTEGER PRIMARY KEY, name TEXT, position TEXT, type INTEGER);.
        /// </summary>
        internal static string mSQLQueryCreateRouteNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateRouteNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS {0}.
        /// </summary>
        internal static string mSQLQueryDropTable {
            get {
                return ResourceManager.GetString("mSQLQueryDropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO buses (id, name, position, velocity, currNumOfPassengers, numOfIncomingPassengers, numOfExcurrentPassengers, maxNumOfPassengers, currRouteNodeIndex) VALUES(@id, @name, @position, @velocity, @currNumOfPassengers, @numOfIncomingPassengers, @numOfExcurrentPassengers, @maxNumOfPassengers, @currRouteNodeIndex).
        /// </summary>
        internal static string mSQLQueryInsertBus {
            get {
                return ResourceManager.GetString("mSQLQueryInsertBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO busStationNodes (id, currNumOfPassengers, intensity) VALUES (@id, @currNumOfPassengers, @intensity).
        /// </summary>
        internal static string mSQLQueryInsertBusStationNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertBusStationNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO crossroadNodes (id, loadCoefficient) VALUES (@id, @loadCoefficient).
        /// </summary>
        internal static string mSQLQueryInsertCrossroadNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertCrossroadNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO routeNodes (id, name, position, type) VALUES(@id, @name, @position, @type).
        /// </summary>
        internal static string mSQLQueryInsertRouteNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertRouteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routeNodes.
        /// </summary>
        internal static string mSQLRouteNodesTableName {
            get {
                return ResourceManager.GetString("mSQLRouteNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_route_button {
            get {
                object obj = ResourceManager.GetObject("open_route_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause_simulation_button {
            get {
                object obj = ResourceManager.GetObject("pause_simulation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap quit_button {
            get {
                object obj = ResourceManager.GetObject("quit_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset_simulation_button {
            get {
                object obj = ResourceManager.GetObject("reset_simulation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_route_button {
            get {
                object obj = ResourceManager.GetObject("save_route_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start_simulation_button {
            get {
                object obj = ResourceManager.GetObject("start_simulation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics_button {
            get {
                object obj = ResourceManager.GetObject("statistics_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics_button_active {
            get {
                object obj = ResourceManager.GetObject("statistics_button_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_simulation_button {
            get {
                object obj = ResourceManager.GetObject("stop_simulation_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
