//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationOfBusRoute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulationOfBusRoute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Animation {
            get {
                object obj = ResourceManager.GetObject("Animation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddBusButton {
            get {
                object obj = ResourceManager.GetObject("mAddBusButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление.
        /// </summary>
        internal static string mAddMode {
            get {
                return ResourceManager.GetString("mAddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddNodeButton {
            get {
                object obj = ResourceManager.GetObject("mAddNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mAddNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mAddNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addRouteNodeButton.
        /// </summary>
        internal static string mAddRouteNodeButtonName {
            get {
                return ResourceManager.GetString("mAddRouteNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mBusEditorButton {
            get {
                object obj = ResourceManager.GetObject("mBusEditorButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автобус № {0}.
        /// </summary>
        internal static string mBusesHeaderInEditor {
            get {
                return ResourceManager.GetString("mBusesHeaderInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decl {{{0}    time : Time;{0}    v : Vector({1});{0}}}.
        /// </summary>
        internal static string mBusesVelocitiesHeaderTemplate {
            get {
                return ResourceManager.GetString("mBusesVelocitiesHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to busesVelocitiesCode.
        /// </summary>
        internal static string mBusesVelocitiesName {
            get {
                return ResourceManager.GetString("mBusesVelocitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mCopyButton {
            get {
                object obj = ResourceManager.GetObject("mCopyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mCutButton {
            get {
                object obj = ResourceManager.GetObject("mCutButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mDataEditorButton {
            get {
                object obj = ResourceManager.GetObject("mDataEditorButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case|default|decl|in.
        /// </summary>
        internal static string mDataEditorHighlightingGroup1 {
            get {
                return ResourceManager.GetString("mDataEditorHighlightingGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time|Matrix|Vector.
        /// </summary>
        internal static string mDataEditorHighlightingGroup2 {
            get {
                return ResourceManager.GetString("mDataEditorHighlightingGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string mDataEditorHighlightingGroup3 {
            get {
                return ResourceManager.GetString("mDataEditorHighlightingGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        internal static string mErrorMessageTitle {
            get {
                return ResourceManager.GetString("mErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finishTimeOfSimulation.
        /// </summary>
        internal static string mFinishTimeOfSimulationOption {
            get {
                return ResourceManager.GetString("mFinishTimeOfSimulationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mLoadRouteButton {
            get {
                object obj = ResourceManager.GetObject("mLoadRouteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matrixOfIntensitiesCode.
        /// </summary>
        internal static string mMatricesOfIntensitiesName {
            get {
                return ResourceManager.GetString("mMatricesOfIntensitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещение.
        /// </summary>
        internal static string mMoveMode {
            get {
                return ResourceManager.GetString("mMoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mMoveNodeButton {
            get {
                object obj = ResourceManager.GetObject("mMoveNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mMoveNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mMoveNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moveNodeButton.
        /// </summary>
        internal static string mMoveNodeButtonName {
            get {
                return ResourceManager.GetString("mMoveNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mPasteButton {
            get {
                object obj = ResourceManager.GetObject("mPasteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mPauseSimulationButton {
            get {
                object obj = ResourceManager.GetObject("mPauseSimulationButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mQuitButton {
            get {
                object obj = ResourceManager.GetObject("mQuitButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mRedoButton {
            get {
                object obj = ResourceManager.GetObject("mRedoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        internal static string mRemoveMode {
            get {
                return ResourceManager.GetString("mRemoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mRemoveNodeButton {
            get {
                object obj = ResourceManager.GetObject("mRemoveNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mRemoveNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mRemoveNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeRouteNodeButton.
        /// </summary>
        internal static string mRemoveRouteNodeButtonName {
            get {
                return ResourceManager.GetString("mRemoveRouteNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mSaveRouteButton {
            get {
                object obj = ResourceManager.GetObject("mSaveRouteButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор.
        /// </summary>
        internal static string mSelectionMode {
            get {
                return ResourceManager.GetString("mSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mSelectNodeButton {
            get {
                object obj = ResourceManager.GetObject("mSelectNodeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mSelectNodeButtonActive {
            get {
                object obj = ResourceManager.GetObject("mSelectNodeButtonActive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectNodeButton.
        /// </summary>
        internal static string mSelectNodeButtonName {
            get {
                return ResourceManager.GetString("mSelectNodeButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mSettingsButton {
            get {
                object obj = ResourceManager.GetObject("mSettingsButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задан неверный временной интервал.
        /// </summary>
        internal static string mSettingsIncorrectTimeIntervalErrorMessage {
            get {
                return ResourceManager.GetString("mSettingsIncorrectTimeIntervalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speedOfSimulation.
        /// </summary>
        internal static string mSpeedOfSimulationOption {
            get {
                return ResourceManager.GetString("mSpeedOfSimulationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buses.
        /// </summary>
        internal static string mSQLBusesTableName {
            get {
                return ResourceManager.GetString("mSQLBusesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to busStationNodes.
        /// </summary>
        internal static string mSQLBusStationNodesTableName {
            get {
                return ResourceManager.GetString("mSQLBusStationNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS textData(name TEXT, value TEXT);.
        /// </summary>
        internal static string mSQLCreateTextDataTable {
            get {
                return ResourceManager.GetString("mSQLCreateTextDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crossroadNodes.
        /// </summary>
        internal static string mSQLCrossroadNodesTableName {
            get {
                return ResourceManager.GetString("mSQLCrossroadNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS buses (id INTEGER PRIMARY KEY, name TEXT, maxNumOfPassengers INTEGER, startTime REAL, alightingTimePerPassenger REAL, boardingTimePerPassenger REAL);.
        /// </summary>
        internal static string mSQLQueryCreateBusesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateBusesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS busStationNodes (id INTEGER, currNumOfPassengers REAL, velocityOfSpan REAL, FOREIGN KEY(id) REFERENCES routeNodes(id) ON DELETE CASCADE ON UPDATE CASCADE);.
        /// </summary>
        internal static string mSQLQueryCreateBusStationNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateBusStationNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS crossroadNodes (id INTEGER, FOREIGN KEY(id) REFERENCES routeNodes(id) ON DELETE CASCADE ON UPDATE CASCADE);.
        /// </summary>
        internal static string mSQLQueryCreateCrossroadNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateCrossroadNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS routeNodes (id INTEGER PRIMARY KEY, name TEXT, position TEXT, type INTEGER);.
        /// </summary>
        internal static string mSQLQueryCreateRouteNodesTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateRouteNodesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS settings(name TEXT PRIMARY KEY, value TEXT);.
        /// </summary>
        internal static string mSQLQueryCreateSettingsTable {
            get {
                return ResourceManager.GetString("mSQLQueryCreateSettingsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS {0}.
        /// </summary>
        internal static string mSQLQueryDropTable {
            get {
                return ResourceManager.GetString("mSQLQueryDropTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO buses (id, name, maxNumOfPassengers, startTime, alightingTimePerPassenger, boardingTimePerPassenger) VALUES(@id, @name, @maxNumOfPassengers, @startTime, @alightingTimePerPassenger, @boardingTimePerPassenger).
        /// </summary>
        internal static string mSQLQueryInsertBus {
            get {
                return ResourceManager.GetString("mSQLQueryInsertBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO busStationNodes (id, currNumOfPassengers, velocityOfSpan) VALUES (@id, @currNumOfPassengers, @velocityOfSpan).
        /// </summary>
        internal static string mSQLQueryInsertBusStationNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertBusStationNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO crossroadNodes (id) VALUES (@id).
        /// </summary>
        internal static string mSQLQueryInsertCrossroadNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertCrossroadNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO routeNodes (id, name, position, type) VALUES(@id, @name, @position, @type).
        /// </summary>
        internal static string mSQLQueryInsertRouteNode {
            get {
                return ResourceManager.GetString("mSQLQueryInsertRouteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO settings(name, value) VALUES(@name, @value).
        /// </summary>
        internal static string mSQLQueryInsertSettings {
            get {
                return ResourceManager.GetString("mSQLQueryInsertSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO textData(name, value) VALUES (@name, @value).
        /// </summary>
        internal static string mSQLQueryInsertTextData {
            get {
                return ResourceManager.GetString("mSQLQueryInsertTextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routeNodes.
        /// </summary>
        internal static string mSQLRouteNodesTableName {
            get {
                return ResourceManager.GetString("mSQLRouteNodesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string mSQLSettingsTableName {
            get {
                return ResourceManager.GetString("mSQLSettingsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}.
        /// </summary>
        internal static string mSQLSimpleSelectQuery {
            get {
                return ResourceManager.GetString("mSQLSimpleSelectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textData.
        /// </summary>
        internal static string mSQLTextDataTableName {
            get {
                return ResourceManager.GetString("mSQLTextDataTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mStartSimulationButton {
            get {
                object obj = ResourceManager.GetObject("mStartSimulationButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startTimeOfSimulation.
        /// </summary>
        internal static string mStartTimeOfSimulationOption {
            get {
                return ResourceManager.GetString("mStartTimeOfSimulationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decl {{{0}    time : Time;{0}    beta : Matrix({1}, {2});{0}}}.
        /// </summary>
        internal static string mStationsDataHeaderTemplate {
            get {
                return ResourceManager.GetString("mStationsDataHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case (&lt;please, type in a condition here&gt;) {{{0}    {1} = [{2}];{0}}}.
        /// </summary>
        internal static string mStationsEditorCaseTemplate {
            get {
                return ResourceManager.GetString("mStationsEditorCaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default {{{0}    {1} = [{2}];{0}}}.
        /// </summary>
        internal static string mStationsEditorDefaultProgramTemplate {
            get {
                return ResourceManager.GetString("mStationsEditorDefaultProgramTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mStatisticsViewerButton {
            get {
                object obj = ResourceManager.GetObject("mStatisticsViewerButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий режим: {0}.
        /// </summary>
        internal static string mStatusLabelMessage {
            get {
                return ResourceManager.GetString("mStatusLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mStopSimulationButton {
            get {
                object obj = ResourceManager.GetObject("mStopSimulationButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mUndoButton {
            get {
                object obj = ResourceManager.GetObject("mUndoButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
